### ISSUE TITLE
KiCad files incompatible

### ISSUE THREAD

**Issue by Xeroxxx** [Wren6991/Pico-DVI-Sock#2]
Hello,
can you check why its not possible to open the files in latest KiCad?

Error message for PCB file is missing symbole and file has been created with a newer version than latest.

Thx

**Comment by Wren6991** [comment]
Like it says at the top of the Readme

> ⚠️ This board was created with KiCad Nightly (5.99). Exported gerbers are in gerb/, so you can order PCBs without installing this version of KiCad.

KiCad 6 is out now, so you should be able to use that if you don't want to install a nightly build
